export const tal = [
    {
    img:'./img/ok.img.svg',
    name: 'Постоянное наличие',
    poragraf: 'Прямая работа с производителем обеспечивает постоянное наличие всех видом металлопроката'
    },
    {
    img:'./img/ok.img.svg',
    name: 'Постоянное наличие',
    poragraf: 'Прямая работа с производителем обеспечивает постоянное наличие всех видом металлопроката'
    },
    {
    img:'./img/ok.img.svg',
    name: 'Постоянное наличие',
    poragraf: 'Прямая работа с производителем обеспечивает постоянное наличие всех видом металлопроката'
    },
    {
    img:'./img/ok.img.svg',
    name: 'Постоянное наличие',
    poragraf: 'Прямая работа с производителем обеспечивает постоянное наличие всех видом металлопроката'
    },
    {
    img:'./img/ok.img.svg',
    name: 'Постоянное наличие',
    poragraf: 'Прямая работа с производителем обеспечивает постоянное наличие всех видом металлопроката'
    },
    {
    img:'./img/ok.img.svg',
    name: 'Постоянное наличие',
    poragraf: 'Прямая работа с производителем обеспечивает постоянное наличие всех видом металлопроката'
    },
];



export const min = [
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },
    {
    img1:'./img/Product.svg',
    name1: 'Металлочерепица Classic',
    brand: "Бренд",
    height: "Высота волны, мм",
    metre: "Высота ступеньки, мм",
    grand: "Grande Line",
    number: "23.5",
    num: "20",
    pub: 'от 433 ₽/м²',
    color: "Цвет",
    input: "",
    width: "Tолщина",
    face: 'Поверхность',
    button: "Рассчитать стоимость",
    buttonn: 'Подробнее о товаре',
    value: 'RAL 7004',
    value3: '0,4',
    value2: 'выбрать',
    },

];